### PR TITLE
Add PHP 8.2 Support, Drop PHP 7.4 Support

### PR DESCRIPTION
**Pull request by gsteel**
|    Q          |   A
|-------------- | ------
| New Feature   | yes
| QA            | yes

### Description

Adds support for PHP 8.2, removing support for PHP 7.4

Support for 8.2 requires declaring the public `$priority` property on all route types.

### CODE REVIEW

**Comment by Ocramius** [comment]
@gsteel looking good: can we :ship: ?

**Comment by gsteel** [comment]
I put this in Draft mode because it depends on laminas-http and i18n. i18n will support 8.2 fine, but I don't know what we're looking at with http. Only trying to avoid ignoring platform reqs, but if that's OK then please go for it!

**Comment by Ocramius** [comment]
IMO OK to ignore platform requirements for now, and move on :+1: 

We will likely introduce better stability as we move on. Alternatively, renovate support will be faster :D

**Review by Ocramius — APPROVED** [review]
:ship:

**Pull request merged**
